export const SONGS = [
  "240.mp3",
  "A_Musical_Journey_(Stereo_FX_Club_Mix).mp3",
  "A_Spiritual_Union.mp3",
  "Acoustic_Techno_Fusion.mp3",
  "Ain't_That_Just_the_Way.mp3",
  "All_We_Hear_Is_Dirty.mp3",
  "Big_Smoke_Stream.mp3",
  "Blue_Money.mp3",
  "Breathing.mp3",
  "Coast_To_Coast_Law.mp3",
  "Crunk_Manifesto.mp3",
  "Crunkadelic.mp3",
  "Dirty_Beats.mp3",
  "Dirty_MF.mp3",
  "DJ_Smoke_Stream.mp3",
  "Do_Ya_Thang_(Orion_Starfall_Remix).mp3",
  "Double_Dutch_Up_The_Cannibus.mp3",
  "Down_South_Mayhem.mp3",
  "Explicit_Lyrics.mp3",
  "F_ck_a_Suit_and_Tie.mp3",
  "Get_Together_Lucky.mp3",
  "Hacken_Delight.mp3",
  "Heatwave.mp3",
  "Hood_Crunk_Legend.mp3",
  "Hood_Mentality.mp3",
  "I'm_Sm0ken420_On_X_.mp3",
  "Inferno_Beat.mp3",
  "Insert_Title_Here.mp3",
  "Jail_Is_Hot.mp3",
  "japanese_gaisha_house_music.mp3",
  "japanese_gaisha_house_spin.mp3",
  "Jungle_Pulse.mp3",
  "Kemuri_(Smoke)_and_Beats.mp3",
  "Kronk_&_Trap__Top_Hits_through_the_Decades.mp3",
  "Latex_&_Bass.mp3",
  "Logical.mp3",
  "Midnight_Cocaine.mp3",
  "Midnight_Fix.mp3",
  "Money_Over_Everything.mp3",
  "Orion's_420_High_Way_.mp3",
  "Resonance_Cascade.mp3",
  "Rhapsody_of_the_Moment.mp3",
  "Rhythm_Switched__.mp3",
  "Shockwave.mp3",
  "Slippin.mp3",
  "Slippin_Sipping_soda.mp3",
  "smoke_stream_media_(1).mp3",
  "smokin'_on_a_higher_plane_club_banger.mp3",
  "smoking-digital-thrones.mp3",
  "Smoken_Tokens_wit_D_Dbl_G.mp3",
  "Southern_Crunk_Anthem.mp3",
  "The_2_O'Clock_Jump.mp3",
  "The_Knickerbocker.mp3",
  "The_OS_of_Funk.mp3",
  "The_Smoke_Stream.mp3",
  "Thug_Hood_Rap_Legends.mp3",
  "Torus_Knot.mp3",
  "Uptown_Dreams_(Are_Made_of_This.mp3",
  "We_Hear_It_All.mp3",
  "We_shoutin'_out_loud.mp3",
  "West_Side_Legends.mp3",
  "Whirlwind.mp3",
  "Within_Havana_Virgin.mp3",
  "Words_pay.mp3",
  "Your_Brand,_Your_Bread.mp3"
];

export const REALM_TYPES = [
  { id: 0, name: "TORUS_KNOT", desc: "Infinite geometric loop" },
  { id: 1, name: "SPIRAL_TUNNEL", desc: "Hypnotic spiral descent" },
  { id: 2, name: "DNA_ARCHIVE", desc: "Double helix code" },
  { id: 3, name: "CYBER_WAVE", desc: "Digital ocean waves" },
  { id: 4, name: "NEURAL_CORE", desc: "Hypersphere brain" },
  { id: 5, name: "VOID_CLOUD", desc: "Cosmic particle field" },
  { id: 6, name: "DATA_PIPE", desc: "Infinite data stream" },
  { id: 7, name: "GEOMETRIC_CAGE", desc: "Fractal containment" },
  { id: 8, name: "FIBONACCI_SPIRAL", desc: "Golden ratio ascension" },
  { id: 9, name: "CRYSTAL_LATTICE", desc: "Molecular structure" },
  { id: 10, name: "VORTEX_RING", desc: "Energy toroid" },
  { id: 11, name: "QUANTUM_FOAM", desc: "Spacetime bubbles" },
  { id: 12, name: "PULSE_SPHERE", desc: "Rhythmic energy sphere" },
  { id: 13, name: "WARP_TUNNEL", desc: "Hyperspace corridor" },
  { id: 14, name: "MATRIX_RAIN", desc: "Digital waterfall" },
  { id: 15, name: "STAR_FIELD", desc: "Endless constellation" },
  { id: 16, name: "HELIX_TOWER", desc: "Ascending spiral tower" },
  { id: 17, name: "PLASMA_GLOBE", desc: "Electric sphere" },
  { id: 18, name: "FRACTAL_TREE", desc: "Branching infinity" },
  { id: 19, name: "NEON_GRID", desc: "Electric matrix grid" },
  { id: 20, name: "COSMIC_WEB", desc: "Universal network" },
  { id: 21, name: "HYPERCUBE", desc: "4D tesseract shadow" },
  { id: 22, name: "AURORA_WAVE", desc: "Polar light stream" },
  { id: 23, name: "MOBIUS_STRIP", desc: "Infinite twisted path" },
  { id: 24, name: "GALAXY_SPIRAL", desc: "Stellar arm rotation" },
  { id: 25, name: "PLASMA_RING", desc: "Charged particle loop" },
  { id: 26, name: "CRYSTAL_CAVE", desc: "Geometric cavern" },
  { id: 27, name: "NEURAL_NET", desc: "Synaptic connections" },
  { id: 28, name: "TIME_VORTEX", desc: "Temporal distortion" },
  { id: 29, name: "LASER_GRID", desc: "Beam intersection" },
  { id: 30, name: "ATOM_CLOUD", desc: "Electron probability" },
  { id: 31, name: "WORMHOLE", desc: "Spacetime bridge" },
  { id: 32, name: "PRISM_CASCADE", desc: "Light refraction" },
  { id: 33, name: "SONIC_SPHERE", desc: "Sound wave sphere" },
  { id: 34, name: "DATA_STORM", desc: "Information cyclone" },
  { id: 35, name: "BYTE_STREAM", desc: "Binary flow" },
  { id: 36, name: "PLASMA_FIELD", desc: "Ionized atmosphere" },
  { id: 37, name: "DIMENSION_RIFT", desc: "Reality tear" },
  { id: 38, name: "SINGULARITY", desc: "Gravitational collapse" },
  { id: 39, name: "PHOTON_SWARM", desc: "Light particle cloud" },
  { id: 40, name: "CYBER_LOTUS", desc: "Digital flower bloom" },
  { id: 41, name: "VOID_SPHERE", desc: "Empty space bubble" },
  { id: 42, name: "ENERGY_PULSE", desc: "Radiating waves" },
  { id: 43, name: "TECH_MANDALA", desc: "Sacred geometry" },
  { id: 44, name: "PARTICLE_BEAM", desc: "Accelerator stream" },
  { id: 45, name: "CRYSTAL_SPIRE", desc: "Mineral tower" },
  { id: 46, name: "GRAVITY_WELL", desc: "Curved spacetime" },
  { id: 47, name: "NEON_STORM", desc: "Electric tempest" },
  { id: 48, name: "QUANTUM_GATE", desc: "Portal threshold" },
  { id: 49, name: "HOLO_SPHERE", desc: "Holographic projection" },
  { id: 50, name: "FLUX_FIELD", desc: "Magnetic distortion" },
  { id: 51, name: "STAR_BURST", desc: "Supernova explosion" },
  { id: 52, name: "CODE_HELIX", desc: "Binary spiral" },
  { id: 53, name: "VOID_RING", desc: "Empty circle" },
  { id: 54, name: "PULSE_CUBE", desc: "Rhythmic polyhedron" },
  { id: 55, name: "WARP_SPHERE", desc: "Distorted bubble" },
  { id: 56, name: "LASER_WEB", desc: "Light network" },
  { id: 57, name: "PLASMA_TUBE", desc: "Energy conduit" },
  { id: 58, name: "CYBER_STORM", desc: "Digital hurricane" },
  { id: 59, name: "ATOM_SPHERE", desc: "Nuclear structure" },
  { id: 60, name: "LIGHT_TUNNEL", desc: "Photon passage" },
  { id: 61, name: "FRACTAL_VOID", desc: "Infinite recursion" },
  { id: 62, name: "SONIC_RING", desc: "Audio resonance" },
  { id: 63, name: "DATA_VORTEX", desc: "Information spiral" },
  { id: 64, name: "NEON_PULSE", desc: "Electric heartbeat" },
  { id: 65, name: "QUANTUM_WAVE", desc: "Probability field" },
  { id: 66, name: "COSMIC_GATE", desc: "Universal portal" },
];
